const { Client } = require('pg');

const sql = `
-- Create Blocked Days table
CREATE TABLE IF NOT EXISTS public.blocked_days (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  date TEXT UNIQUE NOT NULL, -- Format: YYYY-MM-DD
  reason TEXT DEFAULT 'Owner unavailable',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- RLS for Blocked Days
ALTER TABLE public.blocked_days ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Anyone can view blocked days." ON public.blocked_days FOR SELECT USING (true);
`;

const client = new Client({
  connectionString: "postgresql://postgres:thebarbercraft2016@db.roxoqyegcrhpfzcofltd.supabase.co:5432/postgres"
});

async function run() {
  try {
    await client.connect();
    console.log("Connected to database.");
    await client.query(sql);
    console.log("Blocked days table created!");
  } catch (err) {
    console.error("Error:", err.message);
  } finally {
    await client.end();
  }
}

run();
