const { Client } = require('pg');

const sql = `
-- 1. Create Profiles table
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
  name TEXT,
  email TEXT UNIQUE,
  phone TEXT,
  role TEXT DEFAULT 'customer',
  wallet_balance DECIMAL(10,2) DEFAULT 0.00,
  rewards_points INTEGER DEFAULT 0,
  is_subscriber BOOLEAN DEFAULT FALSE,
  subscription_expiry TIMESTAMPTZ,
  haircuts_left INTEGER DEFAULT 0,
  beard_trims_left INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Create Bookings table
CREATE TABLE IF NOT EXISTS public.bookings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  booking_id TEXT UNIQUE NOT NULL,
  user_id UUID REFERENCES auth.users ON DELETE SET NULL,
  customer_name TEXT,
  service TEXT NOT NULL,
  date TEXT NOT NULL,
  time TEXT NOT NULL,
  barber TEXT NOT NULL,
  status TEXT DEFAULT 'confirmed',
  payment_status TEXT DEFAULT 'pending',
  advance_amount DECIMAL(10,2) DEFAULT 0.00,
  points_to_earn INTEGER DEFAULT 10,
  is_free BOOLEAN DEFAULT FALSE,
  rebook_deadline TIMESTAMPTZ,
  wallet_transferred BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Create Reward Redemptions table
CREATE TABLE IF NOT EXISTS public.reward_redemptions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users ON DELETE CASCADE,
  service TEXT NOT NULL,
  points_used INTEGER NOT NULL,
  status TEXT DEFAULT 'active',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- RLS Policies
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public profiles are viewable by everyone." ON public.profiles;
CREATE POLICY "Public profiles are viewable by everyone." ON public.profiles FOR SELECT USING (true);
DROP POLICY IF EXISTS "Users can update own profile." ON public.profiles;
CREATE POLICY "Users can update own profile." ON public.profiles FOR UPDATE USING (auth.uid() = id);

ALTER TABLE public.bookings ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Users can see their own bookings." ON public.bookings;
CREATE POLICY "Users can see their own bookings." ON public.bookings FOR SELECT USING (auth.uid() = user_id);
DROP POLICY IF EXISTS "Users can insert their own bookings." ON public.bookings;
CREATE POLICY "Users can insert their own bookings." ON public.bookings FOR INSERT WITH CHECK (auth.uid() = user_id);

ALTER TABLE public.reward_redemptions ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Users can see their redemptions." ON public.reward_redemptions;
CREATE POLICY "Users can see their redemptions." ON public.reward_redemptions FOR SELECT USING (auth.uid() = user_id);
`;

const client = new Client({
  connectionString: "postgresql://postgres:thebarbercraft2016@db.roxoqyegcrhpfzcofltd.supabase.co:5432/postgres"
});

async function run() {
  try {
    await client.connect();
    console.log("Connected to database.");
    await client.query(sql);
    console.log("SQL executed successfully! Tables created.");
  } catch (err) {
    console.error("Error executing SQL:", err.message);
  } finally {
    await client.end();
  }
}

run();
